org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.76
neo_version_range=[26.2.0.76,)

mod_id=alchemia
mod_name=Alchemia
mod_license=Blu's License of Common Sense
mod_version=1.0.0
mod_group_id=muddykat.alchemia
mod_authors=Muddykat
mod_description=A tech based mod focused on realism.

jei_version=30.31.0.206
